# Generated by Django 5.1.7 on 2025-04-30 22:53

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkspaceFacilities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('workspace_type', models.CharField(choices=[('Workspace', 'Workspace'), ('Hotdesk', 'Hotdesk')], max_length=9)),
                ('description', models.TextField(blank=True, null=True)),
                ('address_1', models.TextField(blank=True, null=True)),
                ('address_2', models.TextField(blank=True, null=True)),
                ('pincode', models.IntegerField(blank=True, null=True)),
                ('city', models.TextField(blank=True, null=True)),
                ('state', models.TextField(blank=True, null=True)),
                ('country', models.TextField(blank=True, null=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('insta', models.URLField(blank=True, null=True)),
                ('facebook', models.URLField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, default='logo.jpg', null=True, upload_to='workspace\\logos')),
                ('background', models.ImageField(blank=True, default='background.jpg', null=True, upload_to='workspace\\background')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('amenities', models.ManyToManyField(blank=True, related_name='amenitiies', to='workspaces.workspacefacilities')),
            ],
        ),
        migrations.CreateModel(
            name='WorkspaceCapacity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='workspace', max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('capacity', models.IntegerField(blank=True, null=True)),
                ('rate_per_hour', models.IntegerField(blank=True, null=True)),
                ('rate_per_day', models.IntegerField(blank=True, null=True)),
                ('rate_per_month', models.IntegerField(blank=True, null=True)),
                ('workspace', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='capacity', to='workspaces.workspace')),
            ],
        ),
        migrations.CreateModel(
            name='WorkspacePhotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gallery', models.ImageField(upload_to='workspace\\gallery')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='workspaces.workspace')),
            ],
        ),
    ]
